# Generated by Django 4.2.3 on 2023-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribe_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cretated_at',
            new_name='created_at',
        ),
    ]
